// packages/sonik/src/presets/solid/head.tsx
import type { JSX } from 'solid-js'
import { createComponent } from 'solid-js/web'
import { Head as BaseHead } from '../../server/head'

export class Head extends BaseHead {
  constructor() {
    super({
      // createElement and fragment will not be used
      createElement: (type, props) => createComponent(() => type, props),
      fragment: <></>,
    })
  }
  createTags(): JSX.Element {
    return (
      <>
        {this.title ? <title>{this.title}</title> : <></>}
        {this.meta ? this.meta.map((record) => <meta {...record} />) : <></>}
        {this.link ? this.link.map((record) => <meta {...record} />) : <></>}
      </>
    )
  }
}

// src/server/head.tsx
/** @jsx h */
/** @jsxFragment Fragment */
import { h, Fragment } from 'preact'
import type { Head } from '../types'

export const createHeadTag = (head?: Head) => {
  return (
    <Fragment>
      {head && head.title ? <title>{head.title}</title> : <Fragment />}
      {head && head.meta ? (
        head.meta.map((attr) => {
          return <meta {...attr} />
        })
      ) : (
        <Fragment></Fragment>
      )}
      {head && head.link ? (
        head.link.map((attr) => {
          return <link {...attr} />
        })
      ) : (
        <Fragment></Fragment>
      )}
    </Fragment>
  )
}
