// packages/sonik/src/presets/solid/head.tsx
import type { JSX } from 'solid-js'
import { createComponent } from 'solid-js/web'
import { Head as BaseHead } from '../../server/head'

export class Head extends BaseHead {
  constructor() {
    super({
      // createElement and fragment will not be used
      createElement: (type, props) => createComponent(() => type, props),
      fragment: <></>,
    })
  }
  createTags(): JSX.Element {
    return (
      <>
        {this.title ? <title>{this.title}</title> : <></>}
        {this.meta ? this.meta.map((record) => <meta {...record} />) : <></>}
        {this.link ? this.link.map((record) => <meta {...record} />) : <></>}
      </>
    )
  }
}

// packages/sonik/src/server/head.tsx
type HeadData = {
  title?: string
  meta?: Record<string, string>[]
  link?: Record<string, string>[]
}

export class Head {
  #title?: string
  #meta?: Record<string, string>[]
  #link?: Record<string, string>[]

  set(data: HeadData) {
    this.#title = data.title
    this.#meta = data.meta
    this.#link = data.link
  }

  set title(value: string) {
    this.#title = value
  }

  set meta(records: Record<string, string>[]) {
    this.#meta = records
  }

  set link(records: Record<string, string>[]) {
    this.#link = records
  }

  createTags() {
    return (
      <>
        {this.#title ? <title>{this.#title}</title> : <></>}
        {this.#meta ? (
          this.#meta.map((attr) => {
            return <meta {...attr} />
          })
        ) : (
          <></>
        )}
        {this.#link ? (
          this.#link.map((attr) => {
            return <link {...attr} />
          })
        ) : (
          <></>
        )}
      </>
    )
  }
}
